### ISSUE TITLE
"Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by edwinm** [freiksenet/react-kinetic#2]
After a git clone and npm install, the example is still not working.

The implementation of require is missing. It's also not clear which implementation is used.

Please provide this.

**Comment by freiksenet** [comment]
I've added instructions on how to build from source. Note that react-kinetic doesn't yet support any other module systems, but CommonJS. So you need to use webpack or browserify, if you want to use it. I will later add bower distribution that will have UMD module.

**Comment by freiksenet** [comment]
Closed in favour of #4.
