### ISSUE TITLE
Don't use synchronous require

### ISSUE THREAD

**Issue by edwinm** [freiksenet/react-kinetic#3]
In your code you use require, for example:

var ReactKinetic = require('./src/ReactKinetic');

This is synchronous code, which is very bad for performance and is discouraged to use in production code.

Please use an asynchronous loader like requirejs.

http://requirejs.org/

**Comment by freiksenet** [comment]
react-kinetic is using CommonJS, not AMD modules. I am not aware of any performance problems from using CommonJS require this way. This is how they do it in, for example, React.
