### ISSUE TITLE
Provide build directory

### ISSUE THREAD

**Issue by edwinm** [freiksenet/react-kinetic#5]
People on Windows don't have make and bash. And even then, I wonder if 
"npm list > /dev/null 2> /dev/null" will work.

Please provide a build directory in Git with a ready to use react-kinetic.js.

I'm now using http://freiksenet.github.io/react-kinetic/react-kinetic.js, but I don't know how old that version is.

**Comment by freiksenet** [comment]
I've made a new release and added standalone version to downloads here on github.
